[theme]
primaryColor = "#00837B"         
backgroundColor = "#F9FAFB"      
secondaryBackgroundColor = "#FFFFFF" 
textColor = "#111827"            
font = "sans serif"

[server]
toolbarMode = "viewer"
